# Generated by Django 4.2.5 on 2023-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
