# Generated by Django 4.2.5 on 2023-10-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('chessplay', '0002_remove_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_played', to='chessplay.game')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_history', to='registration.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='registration.player')),
            ],
            options={
                'unique_together': {('player', 'game', 'opponent')},
            },
        ),
    ]
